version: "3.8"
services:
    proxy:
        image: jupyterhub/configurable-http-proxy:4.5
        networks:
            - jupyterhub_network_swarm
        ports:
            - mode: host
              protocol: tcp
              published: 8001
              target: 8000
        environment:
            CONFIGPROXY_AUTH_TOKEN: abc123
        command:
            - configurable-http-proxy
            - "--error-target"
            - "http://jupyterhub/hub/error"

        deploy:
            mode: global
            resources:
                limits:
                    cpus: '1.0'
                    memory: 500M
                reservations:
                    cpus: '0.1'
                    memory: 10M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 100s
        
    jupyterhub:
        image: hsz1273327/jupyterhub-for-swarm:4.0.1
        hostname: jupyterhub
        networks:
            - jupyterhub_network_swarm
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "jupyterhub-data:/data"
        environment:
            PROXY_SHOULD_START: "False"
            PROXY_API_URL: http://proxy:8001
            CONFIGPROXY_AUTH_TOKEN: abc123
            SPAWNER_NETWORK_NAME: jupyterhub_network_swarm
            # SPAWNER_NOTEBOOK_IMAGE: hsz1273327/gpu-torch-notebook:pytorch2.0.1-cuda11.8.0-notebook6.5.4
            SPAWNER_NOTEBOOK_IMAGE: hsz1273327/data-analyse-notebook:notebook-6.5.4
            SPAWNER_ENDPOINT_MODE: dnsrr
            SPAWNER_PERSISTENCE_VOLUME_TYPE: local
        deploy:
            endpoint_mode: dnsrr
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '2.0'
                    memory: 500M
                reservations:
                    cpus: '0.1'
                    memory: 10M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 100s

volumes:
    jupyterhub-data:
networks:
    jupyterhub_network_swarm:
        external: true